[project]
name = "law"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=0.9.2",
    "psycopg[binary]>=3.1",
    "python-dotenv>=1.1.1",
    "tqdm>=4.67.1",
]

[project.scripts]
law = "main:main"
[tool.mypy]
mypy_path = "stubs"
