[project]
name = "law"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=0.9.2",
    "psycopg[binary]>=3.1",
    "pydantic>=2.7",
    "chromadb>=0.5.3",
]

[project.scripts]
law = "main:main"
