[project]
name = "law"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.7",
    "langchain>=0.2.6,<0.3",
    "langchain-openai>=0.1.8",
    "langchain-google-genai>=0.0.7",
    "langgraph>=0.6.0,<0.7",
    "python-dotenv>=1.0",
]

[project.scripts]
law = "main:main"
