FROM opensearchproject/opensearch:2.15.0

RUN /usr/share/opensearch/bin/opensearch-plugin install --batch analysis-nori
# RUN /usr/share/opensearch/bin/opensearch-plugin remove opensearch-security || true
